spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}/${DB_SCHEMA_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true

scc:
  bucket:
    name: ${S3_BUCKET_NAME}
    url: ${S3_BUCKET_URL}
    region: eu-west-1
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
  email:
    senderEmail: 2ndclosetclub@gmail.com
    adminEmail: 2ndclosetclub@gmail.com
    region: eu-west-1
    accessKey: ${SES_ACCESS_KEY}
    secretKey: ${SES_SECRET_KEY}

---
keycloak-client:
  server-url: ${KEYCLOAK_BASE_URI}
  username: ${KEYCLOAK_CLIENT_USER_NAME}
  password: ${KEYCLOAK_CLIENT_USER_PASSWORD}
  clientId: ${KEYCLOAK_CLIENT_ID}

keycloak:
  auth-server-url:  ${KEYCLOAK_BASE_URI}
  proxyUrl: ${KEYCLOAK_PROXY_URI}