spring:
  datasource:
    username: TEST
    password: TEST
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306/resource-local
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true

scc:
  bucket:
    name: second-closet-club-images-local
    url: https://second-closet-club-images-local.s3.eu-west-1.amazonaws.com
    region: eu-west-1
    accessKey: AKIAVLRFY5LDOYEHXCWV
    secretKey: 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
  email:
    senderEmail: 2ndclosetclub@gmail.com
    adminEmail: shanequaid@hotmail.com
    region: eu-west-1
    accessKey: AKIAVLRFY5LDKVXPIG5H
    secretKey: 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

---
keycloak-client:
  server-url: http://localhost:8083/auth
  username: TEST
  password: TEST
  clientId: b88ce206-63d6-43b6-87c9-ea09d8c02f32

keycloak:
  auth-server-url:  "http://localhost:8083/auth"
  realm: SecondClosetClub